version: "3.3"
services:
  central:
    image: hades-central
    build: ./Central/.
    network_mode: "host"
    ports:
      - "8080:8080"
  processor:
    image: hades-processor
    build: ./processor/.
    network_mode: "host"

  db:
    image: postgres:15.2-bullseye
    environment: 
      POSTGRES_NAME: HADES_postgres
      POSTGRES_DB: HADES_db
      POSTGRES_USER: HADES_main
      POSTGRES_PASSWORD: notsecret
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./postgres-db:/var/lib/postgresql/data

      
volumes:
  postgres-db:
    driver: local
