version: "3.0"
services:
  central:
    image: hades-central
    build: ./Central/.
    network_mode: "host"
    ports:
      - "8080:8080"
  processor:
    image: hades-processor
    build: ./processor/.
    network_mode: "host"

  db:
    image: postgres:15.2-bullseye
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/data/postgres
    environment:
      POSTGRES_USER: HADES_main
      POSTGRES_PASSWORD: notsecret
      POSTGRES_DB: HADES_db
      PGDATA: /data/postgres
    user: 1000:1000
      
volumes:
  postgres-db:
    driver: local
